name: ${project.name}
description: ${project.description}
version: ${project.version}
main: org.avarion.graves.Graves
api-version: 1.18
author: sdtv
load: POSTWORLD


softdepend:
  - PlaceholderAPI

commands:
  graves:
    description: Graves command
    usage: /graves
    aliases:
      - grave
      - tombstones
      - tombstone
      - deathchests
      - deathchest
      - deaths
      - death
      - tombs
      - tomb
      - dc

permissions:
  graves.bypass:
    default: op
    description: Bypass grave protection timers and open any grave.
